# Generated by Django 2.1.5 on 2019-01-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20190111_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_name',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_status',
            field=models.BooleanField(default=False),
        ),
    ]
